<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <style>
            *,::after,::before{
                box-sizing:border-box
            }
            html{
                font-family:sans-serif;
                line-height:1.15;
                -webkit-text-size-adjust:100%;
                -ms-text-size-adjust:100%;
                -ms-overflow-style:scrollbar;
                -webkit-tap-highlight-color:transparent
            }
            body{
                font-family:Open Sans,sans-serif;
                font-size:1rem;
                font-weight:400;
                line-height:1.5;
                margin:0;
                text-align:left;
                color:#525f7f;
                background-color:#f8f9fe
            }
            [tabindex='-1']:focus{
                outline:0!important
            }
            h1,h3,h4,h5,h6{
                margin-top:0;
                margin-bottom:.5rem
            }
            [hidden]{
                display:none!important
            }
            .h1,.h3,.h4,.h5,.h6,h1,h3,h4,h5,h6{
                font-family:inherit;
                font-weight:600;
                line-height:1.5;
                margin-bottom:.5rem;
                color:#32325d
            }
            .h1,h1{
                font-size:1.625rem
            }
            .h3,h3{
                font-size:1.0625rem
            }
            .h4,h4{
                font-size:.9375rem
            }
            .h5,h5{
                font-size:.8125rem
            }
            .h6,h6{
                font-size:.625rem
            }
            @keyframes progress-bar-stripes{
                from{
                    background-position:1rem 0
                }
                to{
                    background-position:0 0
                }
            }
            .my-4{
                margin-top:1.5rem!important
            }
            .my-4{
                margin-bottom:1.5rem!important
            }
            @media print{
                *,::after,::before{
                    box-shadow:none!important;
                    text-shadow:none!important
                }
                h3{
                    orphans:3;
                    widows:3
                }
                h3{
                    page-break-after:avoid
                }
                @page{
                    size:a3
                }
                body{
                    min-width:992px!important
                }
            }
            [class*=shadow]{
                transition:all .15s ease
            }
            [class*=btn-outline-]{
                border-width:1px
            }
            @keyframes show-navbar-collapse{
                0%{
                    transform:scale(.95);
                    transform-origin:100% 0;
                    opacity:0
                }
                100%{
                    transform:scale(1);
                    opacity:1
                }
            }
            @keyframes hide-navbar-collapse{
                from{
                    transform:scale(1);
                    transform-origin:100% 0;
                    opacity:1
                }
                to{
                    transform:scale(.95);
                    opacity:0
                }
            }
            :root{
                --blue:#05445e;
                --white:#fff;
                --gray:#f5f5f5;
                --black1:#222;
                --black2:#999
            }
            .cardheader h2{
                font-weight:600;
                color:var(--blue)
            }
            td{
                text-align:center
            }
        </style>
    </head>
    <body>
        <div class="recent">
            <div class="cardheader">
                <h2>My Reservation History</h2>
            </div>
            <table>
                <thead>
                    <tr>
                        <td>From</td>
                        <td>To</td>
                        <td>Departure</td>
                        <td>Return</td>
                        <td>Adults</td>
                        <td>Children</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Colombo</td>
                        <td>England</td>
                        <td>16/03/2022</td>
                        <td>18/03/2022</td>
                        <td>2</td>
                        <td>1</td>
                    </tr>
                </tbody>
                <tbody>
                    <tr>
                        <td>Colombo</td>
                        <td>England</td>
                        <td>16/03/2022</td>
                        <td>18/03/2022</td>
                        <td>2</td>
                        <td>1</td>
                    </tr>
                </tbody>

                <tbody>
                    <tr>
                        <td>Colombo</td>
                        <td>England</td>
                        <td>16/03/2022</td>
                        <td>18/03/2022</td>
                        <td>2</td>
                        <td>1</td>
                    </tr>
                </tbody>

                <tbody>
                    <tr>
                        <td>Colombo</td>
                        <td>England</td>
                        <td>16/03/2022</td>
                        <td>18/03/2022</td>
                        <td>2</td>
                        <td>1</td>
                    </tr>
                </tbody>
                <tbody>
                    <tr>
                        <td>Colombo</td>
                        <td>England</td>
                        <td>16/03/2022</td>
                        <td>18/03/2022</td>
                        <td>2</td>
                        <td>1</td>
                    </tr>
                </tbody>
                <tbody>
                    <tr>
                        <td>Colombo</td>
                        <td>England</td>
                        <td>16/03/2022</td>
                        <td>18/03/2022</td>
                        <td>2</td>
                        <td>1</td>
                    </tr>
                </tbody>
                <tbody>
                    <tr>
                        <td>Colombo</td>
                        <td>England</td>
                        <td>16/03/2022</td>
                        <td>18/03/2022</td>
                        <td>2</td>
                        <td>1</td>
                    </tr>
                </tbody>
                <tbody>
                    <tr>
                        <td>Colombo</td>
                        <td>England</td>
                        <td>16/03/2022</td>
                        <td>18/03/2022</td>
                        <td>2</td>
                        <td>1</td>
                    </tr>
                </tbody>
                <tbody>
                    <tr>
                        <td>Colombo</td>
                        <td>England</td>
                        <td>16/03/2022</td>
                        <td>18/03/2022</td>
                        <td>2</td>
                        <td>1</td>
                    </tr>
                </tbody>
                <tbody>
                    <tr>
                        <td>Colombo</td>
                        <td>England</td>
                        <td>16/03/2022</td>
                        <td>18/03/2022</td>
                        <td>2</td>
                        <td>1</td>
                    </tr>
                </tbody>
                <tbody>
                    <tr>
                        <td>Colombo</td>
                        <td>England</td>
                        <td>16/03/2022</td>
                        <td>18/03/2022</td>
                        <td>2</td>
                        <td>1</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </body>
</html>
